### ISSUE TITLE
How to add exclude?

### ISSUE THREAD

**Issue by Troyhy** [odwyersoftware/brunette#11]
I would like to exclude directories like \*/migrations/\*
How to do this in setup.cfg?

**Comment by Troyhy** [comment]
```
[tool:brunette]
line-length = 120
verbose = true
single-quotes = true
exclude = .*/migrations/.*
```
Ok, there was a hint that it has to be regular expression format... but more complete example would be nice

**Comment by richardARPANET** [comment]
The config just supports all the same values that 'black' does, so its best to refer to the black documentation for available options and their valid inputs.
