### ISSUE TITLE
black version pin is restrictive. necessary?

### ISSUE THREAD

**Issue by billhunekepf** [odwyersoftware/brunette#15]
Thank you for writing this wrapper for `black` .  I wanted to raise one small suggestion: your requirements file should not pin the black version.  

Perhaps your tool can concern itself only with its compatibility with the parts of the Black api and application surface area that it needs to use, but aside from setting a minimum Black version (and possibly a max version, if necessary) I'd argue that you can leave the specific Black version up to your users.

I'm suggesting changing 

_requirements.txt_
```
setuptools
wheel
black==20.8b1
click
```

to

```
setuptools
wheel
black>=20.8b1
click
```

Hopefully, you can pin the *dev copy*, so that formatting of `brunette` source code remains fixed.  Ie. hopefully there's nothing wrong with this change:

_requirements-dev.txt_
```
black==20.8b1
```

**Comment by richardARPANET** [comment]
fixed in 0.2.1
