### ISSUE TITLE
Support both tool:brunette and brunette section in setup.ini

### ISSUE THREAD

**Issue by iamdavidcz** [odwyersoftware/brunette#7]
Hi,

isort supports [both](https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L48) `isort` and `tool:isort` of the setup.cfg file. Can we also add support for both `brunette` and `tool:brunette`? Currently only `tool:brunette` is supported AFAIK. It's a small change, but it would be more consistent with tools that don't use `tool:` prefix in the setup.ini file.

Thanks!

**Comment by richardARPANET** [comment]
@iamdavidcz Feel free to add this if you like.

**Comment by JulianVolodia** [comment]
@richardARPANET there is also toml `FALLBACK_CONFIG_SECTIONS: Tuple[str, ...] = ("isort", "tool:isort", "tool.isort")` should we implement that, too?

**Comment by JulianVolodia** [comment]
...or remove support for toml conf? :P

**Comment by richardARPANET** [comment]
Closing this issue as it's old. But feel free to add this feature.
